general:
  load_from_scratch: False

directories:
  logs_dir: logs
  output_dir: output

urls:
  racebest_base_url: https://racebest.com
  ukresults_base_url: https://www.ukresults.net
  runbritain_base_url: https://www.runbritainrankings.com/results

shelves:
  racebest_headers: test-pages/racebest/headerrows
  ukresults_headers: test-pages/ukresults/headerrows
